name: Demo Svelte Migration Action

on:
  pull_request:
    paths:
      - "test/**/*.svelte"
      - "test/**/*.ts"
      - "test/**/*.js"

jobs:
  svelte-migration-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build action
        run: pnpm build

      - name: Run Svelte Migration Analysis
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths: test/src
          fail-on-error: false
          fail-on-warning: false
